# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="jeff"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(vi-mode git-flow git-extras brew pip django fabric npm gem heroku rvm adb pod bower history-substring-search go lein foreman yo)

# Options
# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
# Import local settings file if it exists
if [ -f ~/.local-settings ]; then
    source ~/.local-settings
fi

# Custom key bindings
# Serach history
bindkey '^R' history-incremental-pattern-search-backward
bindkey '^S' history-incremental-pattern-search-forward
# Add emacs key bindings that I'm used to
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line
# Jump words
bindkey '^[[1;9C' forward-word
bindkey '^[[1;9D' backward-word

# Aliases
alias zshconfig="vim ~/.zshrc"
alias reloadzshconf="source ~/.zshrc"
alias checksharing='grep ip_address /private/var/db/dhcpd_leases | cut -d= -f2 | nmap -iL - -sn'
alias getip='ipconfig getifaddr en1'
alias getipwired='ipconfig getifaddr en0'
alias getipextern='curl icanhazip.com'
alias getgateway='netstat -nr | grep default'
alias bower='noglob bower'
alias redisdev='redis-server /usr/local/etc/redis.conf'
alias gitjk="fc -l -10 | tail -r | gitjk_cmd"
alias g="git"
alias cleanpython="find . -name '*.pyc' -print0 | xargs -0 rm"
#alias vim="vimr"

whichll() {
	which $* | xargs ls -lG
}

# Some ls aliases
alias ls='ls -G'
alias lla='ls -la'

# List all the processes that are listening and on what port
alias listening='lsof -i -n -P | grep LISTEN'

# See why computer won't sleep
alias whyunosleep='pmset -g assertions'

# Connection and speed tests
alias pg='ping -c 5 google.com'
alias speedtest='curl -o /dev/null http://speedtest.wdc01.softlayer.com/downloads/test500.zip'
alias speedtestwget='wget --output-document=/dev/null http://speedtest.wdc01.softlayer.com/downloads/test500.zip'

# pip
alias pipfreezereqs='pip freeze > requirements.txt'

# Routing
alias routingtable='netstat -nr -f inet'
alias routingtableall='netstat -nr'

# Custom app open stuff
alias st='open -a /Applications/SourceTree.app ./'

# Virtual Env stuff
VIRTUAL_ENV_WRAPPER_PATH=/usr/local/bin/virtualenvwrapper.sh
if [ -f $VIRTUAL_ENV_WRAPPER_PATH ]; then
    export WORKON_HOME=$HOME/.virtualenvs
    export PROJECT_HOME=$HOME
    source $VIRTUAL_ENV_WRAPPER_PATH
fi

# Commands to get terminal tabs to open in the same working directory
precmd () {print -Pn "\e]2; %~/ \a"}
preexec () {print -Pn "\e]2; %~/ \a"}

# Add RVM to PATH for scripting
PATH=$PATH:$HOME/.rvm/bin

# Homebrew
# Hide homebrew beer mug emoji
export HOMEBREW_NO_EMOJI=1
# Homebrew cask
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# Pyenv stuff
# Use homebrew directory for pyenv
#if command -v pyenv > /dev/null; then
    #export PYENV_ROOT=/usr/local/opt/pyenv
    #eval "$(pyenv init -)"
#fi
#if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# gnu coreutils stuff
# use the coreutils commands with their normal names instead of with the g prefix
#PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
# access the coreutils man pages with their normal names
#MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

# Go stuff
export PATH=$PATH:/usr/local/Cellar/go/1.2.1/libexec/bin
export GOPATH=$HOME/dev/go-shenanigans:$HOME/dev/project-euler/go
